version: "3.4"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${ROOT}/config/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
     - 51820:51820/udp
     - 9091:9091
     - 51413:51413
     - 51413:51413/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/storage:/downloads # downloads ***downloads=storage***
      - ${ROOT}/config/transmission:/config # config files
    network_mode: service:wireguard
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /mnt/storage:/downloads # downloads ***downloads=storage***
      - ${ROOT}/config/deluge:/config # config files
    ports:
      - 53394:53394
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/storage:/downloads # to access existing shows
      - ${ROOT}/config/jackett:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - /mnt/storage:/downloads # to access existing shows

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - /mnt/storage:/downloads # to access existing shows

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=000 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config # config files
      - /mnt/storage:/downloads # to access existing shows
    ports:
      - 6767:6767
  
  filebrowser:
    container_name: filebrowser
    hostname: filebrowser
    restart: always
    image: filebrowser/filebrowser
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    ports:
      - 8002:80
    volumes:
      - /mnt/storage/shared:/files/shared
      - /mnt/storage/AnimeBytes Music:/files/music
      - /mnt/storage/Touhou/Touhou lossless music collection:/files/Touhou lossless music collection
      - /mnt/storage/Touhou Torrents:/files/Touhou Torrents
      - ${ROOT}/config/filebrowser/database.db:/database.db
      - ${ROOT}/config/filebrowser/filebrowser.json:/.filebrowser.json
    restart: unless-stopped

  airsonic:
    image: lscr.io/linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${ROOT}/config/airsonic:/config
      - /mnt/storage/Touhou:/Touhou
      - /mnt/storage/Touhou Torrents/ZUN Touhou Official Music Collection:/ZUN
      - /mnt/storage/Touhou lossless music collection:/Touhou2
      - /mnt/storage/AnimeBytes Music:/AnimeBytes Music
      - /mnt/storage/Music:/Music
    ports:
      - 4040:4040
    restart: unless-stopped

